// source: anchortype.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var usertype_pb = require('./usertype_pb.js');
goog.object.extend(proto, usertype_pb);
goog.exportSymbol('proto.pb.AnchorBasic', null, global);
goog.exportSymbol('proto.pb.AnchorProfile', null, global);
goog.exportSymbol('proto.pb.OnlineRecord', null, global);
goog.exportSymbol('proto.pb.SettleRecord', null, global);
goog.exportSymbol('proto.pb.SettleStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.AnchorBasic = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.AnchorBasic.repeatedFields_, null);
};
goog.inherits(proto.pb.AnchorBasic, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.AnchorBasic.displayName = 'proto.pb.AnchorBasic';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.AnchorProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.AnchorProfile.repeatedFields_, null);
};
goog.inherits(proto.pb.AnchorProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.AnchorProfile.displayName = 'proto.pb.AnchorProfile';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.OnlineRecord = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.OnlineRecord, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.OnlineRecord.displayName = 'proto.pb.OnlineRecord';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SettleRecord = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SettleRecord, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.SettleRecord.displayName = 'proto.pb.SettleRecord';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.AnchorBasic.repeatedFields_ = [14,24,100,101];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.AnchorBasic.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.AnchorBasic.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.AnchorBasic} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.AnchorBasic.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    appId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    version: jspb.Message.getFieldWithDefault(msg, 3, 0),
    guildId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    areaId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    robot: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    country: jspb.Message.getFieldWithDefault(msg, 7, ""),
    onlineStatus: jspb.Message.getFieldWithDefault(msg, 8, 0),
    reviewStatus: jspb.Message.getFieldWithDefault(msg, 9, 0),
    profileCount: jspb.Message.getFieldWithDefault(msg, 10, 0),
    activeCount: jspb.Message.getFieldWithDefault(msg, 11, 0),
    level: jspb.Message.getFieldWithDefault(msg, 12, 0),
    lang: jspb.Message.getFieldWithDefault(msg, 13, ""),
    langsList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    price: jspb.Message.getFieldWithDefault(msg, 15, 0),
    callIncome: jspb.Message.getFieldWithDefault(msg, 16, 0),
    giftIncome: jspb.Message.getFieldWithDefault(msg, 17, 0),
    commissionIncome: jspb.Message.getFieldWithDefault(msg, 18, 0),
    adjustIncome: jspb.Message.getFieldWithDefault(msg, 19, 0),
    balance: jspb.Message.getFieldWithDefault(msg, 20, 0),
    settled: jspb.Message.getFieldWithDefault(msg, 21, 0),
    settledAt: jspb.Message.getFieldWithDefault(msg, 22, 0),
    fansCount: jspb.Message.getFieldWithDefault(msg, 23, 0),
    liveIdsList: (f = jspb.Message.getRepeatedField(msg, 24)) == null ? undefined : f,
    offlineAt: jspb.Message.getFieldWithDefault(msg, 25, 0),
    blockStatus: jspb.Message.getFieldWithDefault(msg, 26, 0),
    onlineIp: jspb.Message.getFieldWithDefault(msg, 27, ""),
    longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 28, 0.0),
    latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 29, 0.0),
    createIp: jspb.Message.getFieldWithDefault(msg, 30, ""),
    deviceId: jspb.Message.getFieldWithDefault(msg, 31, 0),
    networkType: jspb.Message.getFieldWithDefault(msg, 32, 0),
    bankName: jspb.Message.getFieldWithDefault(msg, 33, ""),
    accountName: jspb.Message.getFieldWithDefault(msg, 34, ""),
    bankAccount: jspb.Message.getFieldWithDefault(msg, 35, ""),
    email: jspb.Message.getFieldWithDefault(msg, 36, ""),
    note: jspb.Message.getFieldWithDefault(msg, 37, ""),
    heartbeatAt: jspb.Message.getFieldWithDefault(msg, 38, 0),
    accessToken: jspb.Message.getFieldWithDefault(msg, 39, ""),
    accessExpireAt: jspb.Message.getFieldWithDefault(msg, 40, 0),
    agoraRtmToken: jspb.Message.getFieldWithDefault(msg, 41, ""),
    agoraRtmExpireAt: jspb.Message.getFieldWithDefault(msg, 42, 0),
    rcToken: jspb.Message.getFieldWithDefault(msg, 43, ""),
    rcExpireAt: jspb.Message.getFieldWithDefault(msg, 44, 0),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 60, 0),
    createdAt: jspb.Message.getFieldWithDefault(msg, 61, 0),
    toyaId: jspb.Message.getFieldWithDefault(msg, 62, 0),
    toyaSyncedAt: jspb.Message.getFieldWithDefault(msg, 63, 0),
    toyaStatus: jspb.Message.getFieldWithDefault(msg, 64, 0),
    profilesList: jspb.Message.toObjectList(msg.getProfilesList(),
    proto.pb.AnchorProfile.toObject, includeInstance),
    livesList: jspb.Message.toObjectList(msg.getLivesList(),
    usertype_pb.FileRecord.toObject, includeInstance),
    localCurrency: jspb.Message.getFieldWithDefault(msg, 102, ""),
    localBalance: jspb.Message.getFieldWithDefault(msg, 103, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.AnchorBasic}
 */
proto.pb.AnchorBasic.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.AnchorBasic;
  return proto.pb.AnchorBasic.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.AnchorBasic} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.AnchorBasic}
 */
proto.pb.AnchorBasic.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAppId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVersion(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGuildId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAreaId(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRobot(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountry(value);
      break;
    case 8:
      var value = /** @type {!proto.pb.OnlineStatus} */ (reader.readEnum());
      msg.setOnlineStatus(value);
      break;
    case 9:
      var value = /** @type {!proto.pb.ReviewStatus} */ (reader.readEnum());
      msg.setReviewStatus(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setProfileCount(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setActiveCount(value);
      break;
    case 12:
      var value = /** @type {!proto.pb.AnchorLevel} */ (reader.readEnum());
      msg.setLevel(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setLang(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.addLangs(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPrice(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCallIncome(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGiftIncome(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCommissionIncome(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAdjustIncome(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBalance(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSettled(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSettledAt(value);
      break;
    case 23:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFansCount(value);
      break;
    case 24:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedUint64() : [reader.readUint64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLiveIds(values[i]);
      }
      break;
    case 25:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOfflineAt(value);
      break;
    case 26:
      var value = /** @type {!proto.pb.BlockStatus} */ (reader.readEnum());
      msg.setBlockStatus(value);
      break;
    case 27:
      var value = /** @type {string} */ (reader.readString());
      msg.setOnlineIp(value);
      break;
    case 28:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLongitude(value);
      break;
    case 29:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLatitude(value);
      break;
    case 30:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreateIp(value);
      break;
    case 31:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDeviceId(value);
      break;
    case 32:
      var value = /** @type {!proto.pb.NetworkType} */ (reader.readEnum());
      msg.setNetworkType(value);
      break;
    case 33:
      var value = /** @type {string} */ (reader.readString());
      msg.setBankName(value);
      break;
    case 34:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountName(value);
      break;
    case 35:
      var value = /** @type {string} */ (reader.readString());
      msg.setBankAccount(value);
      break;
    case 36:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 37:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    case 38:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setHeartbeatAt(value);
      break;
    case 39:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccessToken(value);
      break;
    case 40:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAccessExpireAt(value);
      break;
    case 41:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgoraRtmToken(value);
      break;
    case 42:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAgoraRtmExpireAt(value);
      break;
    case 43:
      var value = /** @type {string} */ (reader.readString());
      msg.setRcToken(value);
      break;
    case 44:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRcExpireAt(value);
      break;
    case 60:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUpdatedAt(value);
      break;
    case 61:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCreatedAt(value);
      break;
    case 62:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setToyaId(value);
      break;
    case 63:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setToyaSyncedAt(value);
      break;
    case 64:
      var value = /** @type {!proto.pb.ToyaStatus} */ (reader.readEnum());
      msg.setToyaStatus(value);
      break;
    case 100:
      var value = new proto.pb.AnchorProfile;
      reader.readMessage(value,proto.pb.AnchorProfile.deserializeBinaryFromReader);
      msg.addProfiles(value);
      break;
    case 101:
      var value = new usertype_pb.FileRecord;
      reader.readMessage(value,usertype_pb.FileRecord.deserializeBinaryFromReader);
      msg.addLives(value);
      break;
    case 102:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocalCurrency(value);
      break;
    case 103:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLocalBalance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.AnchorBasic.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.AnchorBasic.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.AnchorBasic} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.AnchorBasic.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getAppId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getGuildId();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getAreaId();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getRobot();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getCountry();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getOnlineStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getReviewStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getProfileCount();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getActiveCount();
  if (f !== 0) {
    writer.writeUint32(
      11,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getLang();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getLangsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      14,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0) {
    writer.writeUint32(
      15,
      f
    );
  }
  f = message.getCallIncome();
  if (f !== 0) {
    writer.writeUint32(
      16,
      f
    );
  }
  f = message.getGiftIncome();
  if (f !== 0) {
    writer.writeUint32(
      17,
      f
    );
  }
  f = message.getCommissionIncome();
  if (f !== 0) {
    writer.writeUint32(
      18,
      f
    );
  }
  f = message.getAdjustIncome();
  if (f !== 0) {
    writer.writeInt32(
      19,
      f
    );
  }
  f = message.getBalance();
  if (f !== 0) {
    writer.writeUint32(
      20,
      f
    );
  }
  f = message.getSettled();
  if (f !== 0) {
    writer.writeUint32(
      21,
      f
    );
  }
  f = message.getSettledAt();
  if (f !== 0) {
    writer.writeUint32(
      22,
      f
    );
  }
  f = message.getFansCount();
  if (f !== 0) {
    writer.writeUint32(
      23,
      f
    );
  }
  f = message.getLiveIdsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      24,
      f
    );
  }
  f = message.getOfflineAt();
  if (f !== 0) {
    writer.writeUint32(
      25,
      f
    );
  }
  f = message.getBlockStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      26,
      f
    );
  }
  f = message.getOnlineIp();
  if (f.length > 0) {
    writer.writeString(
      27,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0.0) {
    writer.writeFloat(
      28,
      f
    );
  }
  f = message.getLatitude();
  if (f !== 0.0) {
    writer.writeFloat(
      29,
      f
    );
  }
  f = message.getCreateIp();
  if (f.length > 0) {
    writer.writeString(
      30,
      f
    );
  }
  f = message.getDeviceId();
  if (f !== 0) {
    writer.writeUint32(
      31,
      f
    );
  }
  f = message.getNetworkType();
  if (f !== 0.0) {
    writer.writeEnum(
      32,
      f
    );
  }
  f = message.getBankName();
  if (f.length > 0) {
    writer.writeString(
      33,
      f
    );
  }
  f = message.getAccountName();
  if (f.length > 0) {
    writer.writeString(
      34,
      f
    );
  }
  f = message.getBankAccount();
  if (f.length > 0) {
    writer.writeString(
      35,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      36,
      f
    );
  }
  f = message.getNote();
  if (f.length > 0) {
    writer.writeString(
      37,
      f
    );
  }
  f = message.getHeartbeatAt();
  if (f !== 0) {
    writer.writeUint32(
      38,
      f
    );
  }
  f = message.getAccessToken();
  if (f.length > 0) {
    writer.writeString(
      39,
      f
    );
  }
  f = message.getAccessExpireAt();
  if (f !== 0) {
    writer.writeUint32(
      40,
      f
    );
  }
  f = message.getAgoraRtmToken();
  if (f.length > 0) {
    writer.writeString(
      41,
      f
    );
  }
  f = message.getAgoraRtmExpireAt();
  if (f !== 0) {
    writer.writeUint32(
      42,
      f
    );
  }
  f = message.getRcToken();
  if (f.length > 0) {
    writer.writeString(
      43,
      f
    );
  }
  f = message.getRcExpireAt();
  if (f !== 0) {
    writer.writeUint32(
      44,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f !== 0) {
    writer.writeUint32(
      60,
      f
    );
  }
  f = message.getCreatedAt();
  if (f !== 0) {
    writer.writeUint32(
      61,
      f
    );
  }
  f = message.getToyaId();
  if (f !== 0) {
    writer.writeUint32(
      62,
      f
    );
  }
  f = message.getToyaSyncedAt();
  if (f !== 0) {
    writer.writeUint32(
      63,
      f
    );
  }
  f = message.getToyaStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      64,
      f
    );
  }
  f = message.getProfilesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      100,
      f,
      proto.pb.AnchorProfile.serializeBinaryToWriter
    );
  }
  f = message.getLivesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      101,
      f,
      usertype_pb.FileRecord.serializeBinaryToWriter
    );
  }
  f = message.getLocalCurrency();
  if (f.length > 0) {
    writer.writeString(
      102,
      f
    );
  }
  f = message.getLocalBalance();
  if (f !== 0) {
    writer.writeUint64(
      103,
      f
    );
  }
};


/**
 * optional uint32 id = 1;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 app_id = 2;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getAppId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setAppId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 version = 3;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 guild_id = 4;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getGuildId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setGuildId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 area_id = 5;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getAreaId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setAreaId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool robot = 6;
 * @return {boolean}
 */
proto.pb.AnchorBasic.prototype.getRobot = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setRobot = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional string country = 7;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setCountry = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional OnlineStatus online_status = 8;
 * @return {!proto.pb.OnlineStatus}
 */
proto.pb.AnchorBasic.prototype.getOnlineStatus = function() {
  return /** @type {!proto.pb.OnlineStatus} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.pb.OnlineStatus} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setOnlineStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional ReviewStatus review_status = 9;
 * @return {!proto.pb.ReviewStatus}
 */
proto.pb.AnchorBasic.prototype.getReviewStatus = function() {
  return /** @type {!proto.pb.ReviewStatus} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.pb.ReviewStatus} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setReviewStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional uint32 profile_count = 10;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getProfileCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setProfileCount = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional uint32 active_count = 11;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getActiveCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setActiveCount = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional AnchorLevel level = 12;
 * @return {!proto.pb.AnchorLevel}
 */
proto.pb.AnchorBasic.prototype.getLevel = function() {
  return /** @type {!proto.pb.AnchorLevel} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {!proto.pb.AnchorLevel} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setLevel = function(value) {
  return jspb.Message.setProto3EnumField(this, 12, value);
};


/**
 * optional string lang = 13;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getLang = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setLang = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * repeated string langs = 14;
 * @return {!Array<string>}
 */
proto.pb.AnchorBasic.prototype.getLangsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 14));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setLangsList = function(value) {
  return jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.addLangs = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.clearLangsList = function() {
  return this.setLangsList([]);
};


/**
 * optional uint32 price = 15;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setPrice = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional uint32 call_income = 16;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getCallIncome = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setCallIncome = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional uint32 gift_income = 17;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getGiftIncome = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setGiftIncome = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


/**
 * optional uint32 commission_income = 18;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getCommissionIncome = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setCommissionIncome = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * optional int32 adjust_income = 19;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getAdjustIncome = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setAdjustIncome = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional uint32 balance = 20;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getBalance = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setBalance = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional uint32 settled = 21;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getSettled = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setSettled = function(value) {
  return jspb.Message.setProto3IntField(this, 21, value);
};


/**
 * optional uint32 settled_at = 22;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getSettledAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setSettledAt = function(value) {
  return jspb.Message.setProto3IntField(this, 22, value);
};


/**
 * optional uint32 fans_count = 23;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getFansCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 23, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setFansCount = function(value) {
  return jspb.Message.setProto3IntField(this, 23, value);
};


/**
 * repeated uint64 live_ids = 24;
 * @return {!Array<number>}
 */
proto.pb.AnchorBasic.prototype.getLiveIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 24));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setLiveIdsList = function(value) {
  return jspb.Message.setField(this, 24, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.addLiveIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 24, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.clearLiveIdsList = function() {
  return this.setLiveIdsList([]);
};


/**
 * optional uint32 offline_at = 25;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getOfflineAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 25, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setOfflineAt = function(value) {
  return jspb.Message.setProto3IntField(this, 25, value);
};


/**
 * optional BlockStatus block_status = 26;
 * @return {!proto.pb.BlockStatus}
 */
proto.pb.AnchorBasic.prototype.getBlockStatus = function() {
  return /** @type {!proto.pb.BlockStatus} */ (jspb.Message.getFieldWithDefault(this, 26, 0));
};


/**
 * @param {!proto.pb.BlockStatus} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setBlockStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 26, value);
};


/**
 * optional string online_ip = 27;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getOnlineIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 27, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setOnlineIp = function(value) {
  return jspb.Message.setProto3StringField(this, 27, value);
};


/**
 * optional float longitude = 28;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 28, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setLongitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 28, value);
};


/**
 * optional float latitude = 29;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 29, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setLatitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 29, value);
};


/**
 * optional string create_ip = 30;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getCreateIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 30, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setCreateIp = function(value) {
  return jspb.Message.setProto3StringField(this, 30, value);
};


/**
 * optional uint32 device_id = 31;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getDeviceId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 31, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setDeviceId = function(value) {
  return jspb.Message.setProto3IntField(this, 31, value);
};


/**
 * optional NetworkType network_type = 32;
 * @return {!proto.pb.NetworkType}
 */
proto.pb.AnchorBasic.prototype.getNetworkType = function() {
  return /** @type {!proto.pb.NetworkType} */ (jspb.Message.getFieldWithDefault(this, 32, 0));
};


/**
 * @param {!proto.pb.NetworkType} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setNetworkType = function(value) {
  return jspb.Message.setProto3EnumField(this, 32, value);
};


/**
 * optional string bank_name = 33;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getBankName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 33, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setBankName = function(value) {
  return jspb.Message.setProto3StringField(this, 33, value);
};


/**
 * optional string account_name = 34;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getAccountName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 34, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setAccountName = function(value) {
  return jspb.Message.setProto3StringField(this, 34, value);
};


/**
 * optional string bank_account = 35;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getBankAccount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 35, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setBankAccount = function(value) {
  return jspb.Message.setProto3StringField(this, 35, value);
};


/**
 * optional string email = 36;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 36, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 36, value);
};


/**
 * optional string note = 37;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 37, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setNote = function(value) {
  return jspb.Message.setProto3StringField(this, 37, value);
};


/**
 * optional uint32 heartbeat_at = 38;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getHeartbeatAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 38, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setHeartbeatAt = function(value) {
  return jspb.Message.setProto3IntField(this, 38, value);
};


/**
 * optional string access_token = 39;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getAccessToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 39, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setAccessToken = function(value) {
  return jspb.Message.setProto3StringField(this, 39, value);
};


/**
 * optional uint32 access_expire_at = 40;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getAccessExpireAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 40, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setAccessExpireAt = function(value) {
  return jspb.Message.setProto3IntField(this, 40, value);
};


/**
 * optional string agora_rtm_token = 41;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getAgoraRtmToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 41, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setAgoraRtmToken = function(value) {
  return jspb.Message.setProto3StringField(this, 41, value);
};


/**
 * optional uint32 agora_rtm_expire_at = 42;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getAgoraRtmExpireAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 42, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setAgoraRtmExpireAt = function(value) {
  return jspb.Message.setProto3IntField(this, 42, value);
};


/**
 * optional string rc_token = 43;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getRcToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 43, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setRcToken = function(value) {
  return jspb.Message.setProto3StringField(this, 43, value);
};


/**
 * optional uint32 rc_expire_at = 44;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getRcExpireAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 44, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setRcExpireAt = function(value) {
  return jspb.Message.setProto3IntField(this, 44, value);
};


/**
 * optional uint32 updated_at = 60;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getUpdatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 60, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 60, value);
};


/**
 * optional uint32 created_at = 61;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getCreatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 61, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 61, value);
};


/**
 * optional uint32 toya_id = 62;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getToyaId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 62, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setToyaId = function(value) {
  return jspb.Message.setProto3IntField(this, 62, value);
};


/**
 * optional uint32 toya_synced_at = 63;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getToyaSyncedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 63, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setToyaSyncedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 63, value);
};


/**
 * optional ToyaStatus toya_status = 64;
 * @return {!proto.pb.ToyaStatus}
 */
proto.pb.AnchorBasic.prototype.getToyaStatus = function() {
  return /** @type {!proto.pb.ToyaStatus} */ (jspb.Message.getFieldWithDefault(this, 64, 0));
};


/**
 * @param {!proto.pb.ToyaStatus} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setToyaStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 64, value);
};


/**
 * repeated AnchorProfile profiles = 100;
 * @return {!Array<!proto.pb.AnchorProfile>}
 */
proto.pb.AnchorBasic.prototype.getProfilesList = function() {
  return /** @type{!Array<!proto.pb.AnchorProfile>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pb.AnchorProfile, 100));
};


/**
 * @param {!Array<!proto.pb.AnchorProfile>} value
 * @return {!proto.pb.AnchorBasic} returns this
*/
proto.pb.AnchorBasic.prototype.setProfilesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 100, value);
};


/**
 * @param {!proto.pb.AnchorProfile=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.AnchorProfile}
 */
proto.pb.AnchorBasic.prototype.addProfiles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 100, opt_value, proto.pb.AnchorProfile, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.clearProfilesList = function() {
  return this.setProfilesList([]);
};


/**
 * repeated FileRecord lives = 101;
 * @return {!Array<!proto.pb.FileRecord>}
 */
proto.pb.AnchorBasic.prototype.getLivesList = function() {
  return /** @type{!Array<!proto.pb.FileRecord>} */ (
    jspb.Message.getRepeatedWrapperField(this, usertype_pb.FileRecord, 101));
};


/**
 * @param {!Array<!proto.pb.FileRecord>} value
 * @return {!proto.pb.AnchorBasic} returns this
*/
proto.pb.AnchorBasic.prototype.setLivesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 101, value);
};


/**
 * @param {!proto.pb.FileRecord=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.FileRecord}
 */
proto.pb.AnchorBasic.prototype.addLives = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 101, opt_value, proto.pb.FileRecord, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.clearLivesList = function() {
  return this.setLivesList([]);
};


/**
 * optional string local_currency = 102;
 * @return {string}
 */
proto.pb.AnchorBasic.prototype.getLocalCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 102, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setLocalCurrency = function(value) {
  return jspb.Message.setProto3StringField(this, 102, value);
};


/**
 * optional uint64 local_balance = 103;
 * @return {number}
 */
proto.pb.AnchorBasic.prototype.getLocalBalance = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 103, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorBasic} returns this
 */
proto.pb.AnchorBasic.prototype.setLocalBalance = function(value) {
  return jspb.Message.setProto3IntField(this, 103, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.AnchorProfile.repeatedFields_ = [14,18,19,100,101];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.AnchorProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.AnchorProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.AnchorProfile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.AnchorProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    appId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    areaId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    anchorId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    parentId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    status: jspb.Message.getFieldWithDefault(msg, 6, 0),
    lang: jspb.Message.getFieldWithDefault(msg, 7, ""),
    gender: jspb.Message.getFieldWithDefault(msg, 8, 0),
    nickname: jspb.Message.getFieldWithDefault(msg, 9, ""),
    signature: jspb.Message.getFieldWithDefault(msg, 10, ""),
    avatar: jspb.Message.getFieldWithDefault(msg, 11, ""),
    occupation: jspb.Message.getFieldWithDefault(msg, 12, 0),
    birthday: jspb.Message.getFieldWithDefault(msg, 13, 0),
    tagsList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    voiceGreeting: jspb.Message.getFieldWithDefault(msg, 15, ""),
    onlineStart: jspb.Message.getFieldWithDefault(msg, 16, 0),
    onlineEnd: jspb.Message.getFieldWithDefault(msg, 17, 0),
    photoIdsList: (f = jspb.Message.getRepeatedField(msg, 18)) == null ? undefined : f,
    videoIdsList: (f = jspb.Message.getRepeatedField(msg, 19)) == null ? undefined : f,
    rejectReason: jspb.Message.getFieldWithDefault(msg, 20, ""),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 30, 0),
    createdAt: jspb.Message.getFieldWithDefault(msg, 31, 0),
    photosList: jspb.Message.toObjectList(msg.getPhotosList(),
    usertype_pb.FileRecord.toObject, includeInstance),
    videosList: jspb.Message.toObjectList(msg.getVideosList(),
    usertype_pb.FileRecord.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.AnchorProfile}
 */
proto.pb.AnchorProfile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.AnchorProfile;
  return proto.pb.AnchorProfile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.AnchorProfile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.AnchorProfile}
 */
proto.pb.AnchorProfile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAppId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAreaId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAnchorId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setParentId(value);
      break;
    case 6:
      var value = /** @type {!proto.pb.ReviewStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLang(value);
      break;
    case 8:
      var value = /** @type {!proto.pb.GenderType} */ (reader.readEnum());
      msg.setGender(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setNickname(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignature(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatar(value);
      break;
    case 12:
      var value = /** @type {!proto.pb.OccupationType} */ (reader.readEnum());
      msg.setOccupation(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBirthday(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.addTags(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setVoiceGreeting(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOnlineStart(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOnlineEnd(value);
      break;
    case 18:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedUint64() : [reader.readUint64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPhotoIds(values[i]);
      }
      break;
    case 19:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedUint64() : [reader.readUint64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addVideoIds(values[i]);
      }
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setRejectReason(value);
      break;
    case 30:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUpdatedAt(value);
      break;
    case 31:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCreatedAt(value);
      break;
    case 100:
      var value = new usertype_pb.FileRecord;
      reader.readMessage(value,usertype_pb.FileRecord.deserializeBinaryFromReader);
      msg.addPhotos(value);
      break;
    case 101:
      var value = new usertype_pb.FileRecord;
      reader.readMessage(value,usertype_pb.FileRecord.deserializeBinaryFromReader);
      msg.addVideos(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.AnchorProfile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.AnchorProfile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.AnchorProfile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.AnchorProfile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getAppId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getAreaId();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getAnchorId();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getParentId();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getLang();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getGender();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getNickname();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getSignature();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getAvatar();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getOccupation();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getBirthday();
  if (f !== 0) {
    writer.writeUint32(
      13,
      f
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      14,
      f
    );
  }
  f = message.getVoiceGreeting();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getOnlineStart();
  if (f !== 0) {
    writer.writeUint32(
      16,
      f
    );
  }
  f = message.getOnlineEnd();
  if (f !== 0) {
    writer.writeUint32(
      17,
      f
    );
  }
  f = message.getPhotoIdsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      18,
      f
    );
  }
  f = message.getVideoIdsList();
  if (f.length > 0) {
    writer.writePackedUint64(
      19,
      f
    );
  }
  f = message.getRejectReason();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f !== 0) {
    writer.writeUint32(
      30,
      f
    );
  }
  f = message.getCreatedAt();
  if (f !== 0) {
    writer.writeUint32(
      31,
      f
    );
  }
  f = message.getPhotosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      100,
      f,
      usertype_pb.FileRecord.serializeBinaryToWriter
    );
  }
  f = message.getVideosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      101,
      f,
      usertype_pb.FileRecord.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 id = 1;
 * @return {number}
 */
proto.pb.AnchorProfile.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 app_id = 2;
 * @return {number}
 */
proto.pb.AnchorProfile.prototype.getAppId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setAppId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 area_id = 3;
 * @return {number}
 */
proto.pb.AnchorProfile.prototype.getAreaId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setAreaId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 anchor_id = 4;
 * @return {number}
 */
proto.pb.AnchorProfile.prototype.getAnchorId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setAnchorId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 parent_id = 5;
 * @return {number}
 */
proto.pb.AnchorProfile.prototype.getParentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setParentId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional ReviewStatus status = 6;
 * @return {!proto.pb.ReviewStatus}
 */
proto.pb.AnchorProfile.prototype.getStatus = function() {
  return /** @type {!proto.pb.ReviewStatus} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.pb.ReviewStatus} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional string lang = 7;
 * @return {string}
 */
proto.pb.AnchorProfile.prototype.getLang = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setLang = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional GenderType gender = 8;
 * @return {!proto.pb.GenderType}
 */
proto.pb.AnchorProfile.prototype.getGender = function() {
  return /** @type {!proto.pb.GenderType} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.pb.GenderType} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setGender = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional string nickname = 9;
 * @return {string}
 */
proto.pb.AnchorProfile.prototype.getNickname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setNickname = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string signature = 10;
 * @return {string}
 */
proto.pb.AnchorProfile.prototype.getSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setSignature = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string avatar = 11;
 * @return {string}
 */
proto.pb.AnchorProfile.prototype.getAvatar = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setAvatar = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional OccupationType occupation = 12;
 * @return {!proto.pb.OccupationType}
 */
proto.pb.AnchorProfile.prototype.getOccupation = function() {
  return /** @type {!proto.pb.OccupationType} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {!proto.pb.OccupationType} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setOccupation = function(value) {
  return jspb.Message.setProto3EnumField(this, 12, value);
};


/**
 * optional uint32 birthday = 13;
 * @return {number}
 */
proto.pb.AnchorProfile.prototype.getBirthday = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setBirthday = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * repeated string tags = 14;
 * @return {!Array<string>}
 */
proto.pb.AnchorProfile.prototype.getTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 14));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setTagsList = function(value) {
  return jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.addTags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.clearTagsList = function() {
  return this.setTagsList([]);
};


/**
 * optional string voice_greeting = 15;
 * @return {string}
 */
proto.pb.AnchorProfile.prototype.getVoiceGreeting = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setVoiceGreeting = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional uint32 online_start = 16;
 * @return {number}
 */
proto.pb.AnchorProfile.prototype.getOnlineStart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setOnlineStart = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional uint32 online_end = 17;
 * @return {number}
 */
proto.pb.AnchorProfile.prototype.getOnlineEnd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setOnlineEnd = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


/**
 * repeated uint64 photo_ids = 18;
 * @return {!Array<number>}
 */
proto.pb.AnchorProfile.prototype.getPhotoIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 18));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setPhotoIdsList = function(value) {
  return jspb.Message.setField(this, 18, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.addPhotoIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 18, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.clearPhotoIdsList = function() {
  return this.setPhotoIdsList([]);
};


/**
 * repeated uint64 video_ids = 19;
 * @return {!Array<number>}
 */
proto.pb.AnchorProfile.prototype.getVideoIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 19));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setVideoIdsList = function(value) {
  return jspb.Message.setField(this, 19, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.addVideoIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 19, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.clearVideoIdsList = function() {
  return this.setVideoIdsList([]);
};


/**
 * optional string reject_reason = 20;
 * @return {string}
 */
proto.pb.AnchorProfile.prototype.getRejectReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setRejectReason = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional uint32 updated_at = 30;
 * @return {number}
 */
proto.pb.AnchorProfile.prototype.getUpdatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 30, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 30, value);
};


/**
 * optional uint32 created_at = 31;
 * @return {number}
 */
proto.pb.AnchorProfile.prototype.getCreatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 31, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 31, value);
};


/**
 * repeated FileRecord photos = 100;
 * @return {!Array<!proto.pb.FileRecord>}
 */
proto.pb.AnchorProfile.prototype.getPhotosList = function() {
  return /** @type{!Array<!proto.pb.FileRecord>} */ (
    jspb.Message.getRepeatedWrapperField(this, usertype_pb.FileRecord, 100));
};


/**
 * @param {!Array<!proto.pb.FileRecord>} value
 * @return {!proto.pb.AnchorProfile} returns this
*/
proto.pb.AnchorProfile.prototype.setPhotosList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 100, value);
};


/**
 * @param {!proto.pb.FileRecord=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.FileRecord}
 */
proto.pb.AnchorProfile.prototype.addPhotos = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 100, opt_value, proto.pb.FileRecord, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.clearPhotosList = function() {
  return this.setPhotosList([]);
};


/**
 * repeated FileRecord videos = 101;
 * @return {!Array<!proto.pb.FileRecord>}
 */
proto.pb.AnchorProfile.prototype.getVideosList = function() {
  return /** @type{!Array<!proto.pb.FileRecord>} */ (
    jspb.Message.getRepeatedWrapperField(this, usertype_pb.FileRecord, 101));
};


/**
 * @param {!Array<!proto.pb.FileRecord>} value
 * @return {!proto.pb.AnchorProfile} returns this
*/
proto.pb.AnchorProfile.prototype.setVideosList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 101, value);
};


/**
 * @param {!proto.pb.FileRecord=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.FileRecord}
 */
proto.pb.AnchorProfile.prototype.addVideos = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 101, opt_value, proto.pb.FileRecord, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.AnchorProfile} returns this
 */
proto.pb.AnchorProfile.prototype.clearVideosList = function() {
  return this.setVideosList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.OnlineRecord.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.OnlineRecord.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.OnlineRecord} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.OnlineRecord.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    areaId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    anchorId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    onlineAt: jspb.Message.getFieldWithDefault(msg, 4, 0),
    duration: jspb.Message.getFieldWithDefault(msg, 5, 0),
    offlineAt: jspb.Message.getFieldWithDefault(msg, 6, 0),
    onlineIp: jspb.Message.getFieldWithDefault(msg, 7, ""),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 20, 0),
    createdAt: jspb.Message.getFieldWithDefault(msg, 21, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.OnlineRecord}
 */
proto.pb.OnlineRecord.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.OnlineRecord;
  return proto.pb.OnlineRecord.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.OnlineRecord} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.OnlineRecord}
 */
proto.pb.OnlineRecord.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAreaId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAnchorId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOnlineAt(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDuration(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOfflineAt(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setOnlineIp(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUpdatedAt(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCreatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.OnlineRecord.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.OnlineRecord.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.OnlineRecord} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.OnlineRecord.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getAreaId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getAnchorId();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getOnlineAt();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getDuration();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getOfflineAt();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getOnlineIp();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f !== 0) {
    writer.writeUint32(
      20,
      f
    );
  }
  f = message.getCreatedAt();
  if (f !== 0) {
    writer.writeUint32(
      21,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.pb.OnlineRecord.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.OnlineRecord} returns this
 */
proto.pb.OnlineRecord.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 area_id = 2;
 * @return {number}
 */
proto.pb.OnlineRecord.prototype.getAreaId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.OnlineRecord} returns this
 */
proto.pb.OnlineRecord.prototype.setAreaId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 anchor_id = 3;
 * @return {number}
 */
proto.pb.OnlineRecord.prototype.getAnchorId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.OnlineRecord} returns this
 */
proto.pb.OnlineRecord.prototype.setAnchorId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 online_at = 4;
 * @return {number}
 */
proto.pb.OnlineRecord.prototype.getOnlineAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.OnlineRecord} returns this
 */
proto.pb.OnlineRecord.prototype.setOnlineAt = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 duration = 5;
 * @return {number}
 */
proto.pb.OnlineRecord.prototype.getDuration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.OnlineRecord} returns this
 */
proto.pb.OnlineRecord.prototype.setDuration = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 offline_at = 6;
 * @return {number}
 */
proto.pb.OnlineRecord.prototype.getOfflineAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.OnlineRecord} returns this
 */
proto.pb.OnlineRecord.prototype.setOfflineAt = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string online_ip = 7;
 * @return {string}
 */
proto.pb.OnlineRecord.prototype.getOnlineIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.OnlineRecord} returns this
 */
proto.pb.OnlineRecord.prototype.setOnlineIp = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional uint32 updated_at = 20;
 * @return {number}
 */
proto.pb.OnlineRecord.prototype.getUpdatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.OnlineRecord} returns this
 */
proto.pb.OnlineRecord.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional uint32 created_at = 21;
 * @return {number}
 */
proto.pb.OnlineRecord.prototype.getCreatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.OnlineRecord} returns this
 */
proto.pb.OnlineRecord.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 21, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SettleRecord.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SettleRecord.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SettleRecord} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SettleRecord.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    areaId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    guildId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    anchorId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    settleAt: jspb.Message.getFieldWithDefault(msg, 5, 0),
    status: jspb.Message.getFieldWithDefault(msg, 6, 0),
    callIncome: jspb.Message.getFieldWithDefault(msg, 7, 0),
    giftIncome: jspb.Message.getFieldWithDefault(msg, 8, 0),
    commissionIncome: jspb.Message.getFieldWithDefault(msg, 9, 0),
    adjustIncome: jspb.Message.getFieldWithDefault(msg, 10, 0),
    adjustment: jspb.Message.getFieldWithDefault(msg, 11, 0),
    settled: jspb.Message.getFieldWithDefault(msg, 12, 0),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 30, 0),
    createdAt: jspb.Message.getFieldWithDefault(msg, 31, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SettleRecord}
 */
proto.pb.SettleRecord.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SettleRecord;
  return proto.pb.SettleRecord.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SettleRecord} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SettleRecord}
 */
proto.pb.SettleRecord.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAreaId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGuildId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAnchorId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSettleAt(value);
      break;
    case 6:
      var value = /** @type {!proto.pb.SettleStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCallIncome(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGiftIncome(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCommissionIncome(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAdjustIncome(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAdjustment(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSettled(value);
      break;
    case 30:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUpdatedAt(value);
      break;
    case 31:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCreatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SettleRecord.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.SettleRecord.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.SettleRecord} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.SettleRecord.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getAreaId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getGuildId();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getAnchorId();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getSettleAt();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getCallIncome();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getGiftIncome();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getCommissionIncome();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getAdjustIncome();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getAdjustment();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getSettled();
  if (f !== 0) {
    writer.writeUint32(
      12,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f !== 0) {
    writer.writeUint32(
      30,
      f
    );
  }
  f = message.getCreatedAt();
  if (f !== 0) {
    writer.writeUint32(
      31,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 area_id = 2;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getAreaId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setAreaId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 guild_id = 3;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getGuildId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setGuildId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 anchor_id = 4;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getAnchorId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setAnchorId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 settle_at = 5;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getSettleAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setSettleAt = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional SettleStatus status = 6;
 * @return {!proto.pb.SettleStatus}
 */
proto.pb.SettleRecord.prototype.getStatus = function() {
  return /** @type {!proto.pb.SettleStatus} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.pb.SettleStatus} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional uint32 call_income = 7;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getCallIncome = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setCallIncome = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint32 gift_income = 8;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getGiftIncome = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setGiftIncome = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 commission_income = 9;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getCommissionIncome = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setCommissionIncome = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 adjust_income = 10;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getAdjustIncome = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setAdjustIncome = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 adjustment = 11;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getAdjustment = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setAdjustment = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional uint32 settled = 12;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getSettled = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setSettled = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional uint32 updated_at = 30;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getUpdatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 30, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 30, value);
};


/**
 * optional uint32 created_at = 31;
 * @return {number}
 */
proto.pb.SettleRecord.prototype.getCreatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 31, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.SettleRecord} returns this
 */
proto.pb.SettleRecord.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 31, value);
};


/**
 * @enum {number}
 */
proto.pb.SettleStatus = {
  SETTLEUNKNOWN: 0,
  SETTLEPREPARE: 1,
  SETTLECANCEL: 2,
  SETTLEDONE: 3,
  SETTLEREVOKED: 4
};

goog.object.extend(exports, proto.pb);
